# Generated by Django 4.2.7 on 2023-12-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0004_cliente_venta_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
